GET http://localhost:5000/users

### 
GET http://localhost:5000/users/1

### 
POST http://localhost/ProjectAkhirPW/admin-create/index.php
Content-Type: application/json

{   
    "nama": "Ararya",
    "kelas": "Aves",
    "fakta_unik": "hai",
    "keterangan": "halo",
    "habitat": "mbois",
    "makanan": "haloo",
    "cara_hidup": "mboiss",
    "reproduksi": "ui",
    "ancaman": "ukk",
    "foto_profil": "asas",
    "foto_halaman": "afaf"
}



### 
PATCH http://localhost:5000/users/1 
Content-Type: application/json

{   
    "nama_depan": "araryap", 
    "nama_belakang": "pramadania", 
    "umur": "233"
}

### 
DELETE http://localhost:5000/users/2